### PR TITLE
fix(manifest): cronjob schema deprecation

### PR DESCRIPTION
**Pull request by georgettica**
in the newer version of k8s, this is the new field scehma

see explanation in https://github.com/fluxcd/flux/issues/3564

### CODE REVIEW

**Comment by georgettica** [comment]
(maybe a better link could be added, but I think this does explain the gist)

**Review by skryvets — APPROVED** [review]
👍 👍 👍

**Comment by skryvets** [comment]
Appreciate you took your time to submit a PR and fix it 👍

**Comment by skryvets** [comment]
Merged

**Pull request merged**
